version: "3.7"
services:
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - PHP_INSTALL_MONGO=${PHP_INSTALL_MONGO}
        - PHP_INSTALL_SOAP=${PHP_INSTALL_SOAP}
    image: setupdocker/php-fpm
    container_name: setupdocker-php-fpm
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - setupdocker

  nginx:
    build:
      context: ./nginx
    container_name: setupdocker-nginx
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "${VARNISH_BACKEND_PORT}:81"
    volumes:
      - ../:/var/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    networks:
      - setupdocker

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/.setupdocker/data/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - setupdocker

networks:
  setupdocker:
    driver: bridge
